# Gin is the web framework
gin:
  # Possible values: "debug", "release"
  mode: debug
  # App running behind a reverse proxy?
  # If set, HTTP Forwarded headers will be respected
  reverse_proxy: false

# If all - run all platforms in one binary. You can pick specific coin handle to run binary only with specific coin
# Example: ethereum
# You can see all the coin handles at coins/coins.yml file
platform: all

# Sentry error tracking
#sentry:
#  dsn: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@sentry.io/xxxxxxx

# The transaction watcher
observer:
  auth: test
  # Don't request blocks older than this
  backlog: 3h
  # Don't request more than N blocks at once
  backlog_max_blocks: 200
  # Max connections to open to API
  stream_conns: 16
  # Block polling interval
  block_poll:
    min: 3s
    max: 30s
  rabbitmq:
    uri: amqp://rabbit:5672
    consumer:
      prefetch_count: 10

storage:
  redis: redis://localhost:6379


etherscan:
  api: https://api-ropsten.etherscan.io


# [BTC] Bitcoin: https://bitcoin.org/ (Blockbook API https://github.com/trezor/blockbook)
bitcointest:
  api: https://tbtc1.trezor.io/api


